/**
 * x402 payment routes.
 *
 * GET  /api/payment/service         - payment service info
 * POST /api/payment/optimize        - PROTECTED by real x402 pipeline
 *                                      (HTTP 402 + Payment-Required without payment,
 *                                       verify → settle → REAL tx ID with payment)
 * GET  /api/payment/:paymentId      - payment status
 * GET  /api/payment/:paymentId/transaction - transaction details
 * GET  /api/payment/:paymentId/status       - payment status
 */
import { Router, Request, Response } from "express";
import { ExpressAdapter } from "@x402/express";
import { config, explorerUrl } from "../config";
import {
  createHTTPResourceServer,
  ensureInitialized,
  buildRequestContext,
} from "../x402/resourceServer";
import {
  createPayment,
  getPayment,
  updatePayment,
} from "../services/paymentStore";
import { authorizeTask, getOptimization } from "../services/optimizerService";
import { v4 as uuidv4 } from "uuid";
import type { PaymentRecord, OptimizeResponse } from "../types";

const router = Router();

/** Read the x402 payment header from the request (SDK reads Payment-Signature/X-Payment). */
function readPaymentHeader(req: Request): string | undefined {
  return req.header("payment-signature") || req.header("x-payment");
}

/**
 * Payment service info.
 */
router.get("/service", (_req: Request, res: Response) => {
  res.json({
    service: "urjasetu-x402-gateway",
    x402Version: config.x402Version,
    scheme: config.scheme,
    network: config.network,
    asset: config.asset,
    facilitator: config.facilitatorUrl,
    receiver: config.receiverAddress,
    price: config.optimizationPrice,
    selfFacilitated: true,
  });
});

/**
 * PROTECTED endpoint: POST /api/payment/optimize
 *
 * WITHOUT payment: returns HTTP 402 with a real x402 Payment-Required header.
 * WITH valid payment: verifies via the in-process facilitator, settles on
 * Algorand Testnet, and returns the REAL transaction ID + authorized task.
 */
router.post("/optimize", async (req: Request, res: Response) => {
  const taskId = req.body.taskId as string;
  if (!taskId) {
    return res.status(400).json({
      error: { code: "bad_request", message: "taskId required" },
    });
  }

  let result;
  try {
    // Lazy-init the HTTP resource server (fetches facilitator /supported once).
    await ensureInitialized();

    const httpServer = createHTTPResourceServer();
    const adapter = new ExpressAdapter(req);
    const context = buildRequestContext(adapter, req.path, req.method, readPaymentHeader(req));

    result = await httpServer.processHTTPRequest(context);
    console.log("[payment-gateway] processHTTPRequest result.type=" + result.type);
    if (result.type === "payment-verified") {
      console.log("[payment-gateway] payment-verified payer=" + (result as any).paymentPayload?.paymentHeader?.slice?.(0, 16));
    }
  } catch (err: any) {
    console.error("[payment-gateway] x402 processing error:", err?.message || err);
    return res.status(502).json({
      error: { code: "facilitator_unavailable", message: err?.message || "payment processing failed" },
    });
  }

  // Unpaid / verification failure / extension mismatch → relay the exact SDK
  // response (HTTP 402 + Payment-Required header generated by the real SDK).
  if (result.type === "payment-error") {
    const { response } = result;
    console.error(
      "[payment-gateway] payment-error relayed: status=" + response.status +
      " body=" + JSON.stringify(response.body) +
      " headers=" + JSON.stringify(response.headers) +
      " isHtml=" + response.isHtml,
    );
    res.status(response.status);
    Object.entries(response.headers).forEach(([key, value]) => res.setHeader(key, value));

    // The x402 SDK sometimes relays a verification/settlement failure as a 402
    // with an EMPTY body but a populated PAYMENT-REQUIRED header. Decode that
    // header so the real rejection reason (e.g. on-chain simulation failure,
    // missing asset, insufficient funds) is surfaced to the client instead of
    // an opaque `{}`.
    let relayBody: any = response.body || {};
    const prHeader: string | undefined =
      (response.headers as Record<string, string>)?.["PAYMENT-REQUIRED"] ||
      (response.headers as Record<string, string>)?.["payment-required"];
    if ((!relayBody || JSON.stringify(relayBody) === "{}") && prHeader) {
      try {
        const decoded = JSON.parse(Buffer.from(prHeader, "base64").toString("utf-8"));
        if (decoded?.error) {
          relayBody = {
            error: {
              code: "payment_required",
              message: decoded.error,
              // Preserve the structured requirement so clients can retry.
              paymentRequired: decoded,
            },
          };
        }
      } catch {
        // leave relayBody as-is
      }
    }
    return response.isHtml ? res.send(response.body) : res.json(relayBody);
  }

  if (result.type === "no-payment-required") {
    return res.status(404).json({ error: { code: "not_protected", message: "route not protected" } });
  }
// ---- payment-verified ----
  const { paymentPayload, paymentRequirements, declaredExtensions, beforeHandlerSettlement } = result;

  const paymentHeader = readPaymentHeader(req) || "";
  const paymentId = uuidv4();
  const record: PaymentRecord = {
    paymentId,
    taskId,
    status: "verifying",
    amount: config.optimizationPrice,
    asset: config.asset,
    network: config.network,
    receiverAddress: config.receiverAddress,
    createdAt: new Date().toISOString(),
  };
  createPayment(record);

  // Settle through the REAL x402 pipeline (facilitator /settle → Algorand Testnet).
  let settle;
  try {
    const httpServer = createHTTPResourceServer();
    settle = await httpServer.processSettlement(
      paymentPayload,
      paymentRequirements,
      declaredExtensions,
      { request: buildRequestContext(new ExpressAdapter(req), req.path, req.method, readPaymentHeader(req)) },
      undefined,
      beforeHandlerSettlement,
    );
  } catch (err: any) {
    console.error("[payment-gateway] settlement error:", err?.message || err);
    updatePayment(paymentId, {
      status: "failed",
      failureReason: err?.message || "settlement error",
    });
    return res.status(402).json({
      error: { code: "settlement_failed", message: err?.message || "settlement failed" },
    });
  }

  if (!settle.success) {
    updatePayment(paymentId, {
      status: "failed",
      failureReason: settle.errorReason || settle.errorMessage || "settlement failed",
    });
    Object.entries(settle.headers || {}).forEach(([key, value]) => res.setHeader(key, value));
    return res.status(402).json({
      error: {
        code: "settlement_failed",
        message: settle.errorMessage || settle.errorReason || "settlement failed",
      },
    });
  }

  const txId = settle.transaction;
  const txExplorerUrl = explorerUrl(txId, settle.network || config.network);

  updatePayment(paymentId, {
    status: "settled",
    txId: txId || undefined,
    explorerUrl: txExplorerUrl,
    payerAddress: settle.payer,
    verifiedAt: new Date().toISOString(),
    settledAt: new Date().toISOString(),
  });
  console.log(
    `[payment-gateway] settlement confirmed paymentId=${paymentId} tx=${txId} payer=${settle.payer || "?"}`,
  );

  // Notify the backend (server-side authorization).
  const authResult = await authorizeTask(paymentId, taskId, txId, paymentHeader, paymentRequirements);

  // Fetch the optimization result for the authorized task.
  const optimizationResult = await getOptimization(taskId);

  // Include the SDK-generated PAYMENT-RESPONSE (settlement receipt) header.
  Object.entries(settle.headers || {}).forEach(([key, value]) => res.setHeader(key, value));

  const response: OptimizeResponse = {
    paymentId,
    taskId,
    paymentStatus: "settled",
    transactionId: txId,
    network: settle.network || config.network,
    asset: config.asset,
    amount: config.optimizationPrice,
    authorizationStatus: authResult.authorized ? "authorized" : "denied",
    optimizationResult: optimizationResult
      ? {
          recommendation: optimizationResult.state || "authorized",
          benefit: optimizationResult.target_energy_wh || 0,
          slot: optimizationResult.earliest_start || "",
        }
      : undefined,
  };

  return res.status(200).json(response);
});

/**
 * Get payment by ID.
 */
router.get("/:paymentId", (req: Request, res: Response) => {
  const payment = getPayment(req.params.paymentId);
  if (!payment) {
    return res.status(404).json({
      error: { code: "not_found", message: "payment not found" },
    });
  }
  return res.json(payment);
});

/**
 * Get transaction details for a payment.
 */
router.get("/:paymentId/transaction", (req: Request, res: Response) => {
  const payment = getPayment(req.params.paymentId);
  if (!payment) {
    return res.status(404).json({
      error: { code: "not_found", message: "payment not found" },
    });
  }
  if (!payment.txId) {
    return res.status(404).json({
      error: { code: "no_transaction", message: "no settled transaction for this payment" },
    });
  }
  return res.json({
    paymentId: payment.paymentId,
    network: payment.network,
    asset: payment.asset,
    amount: payment.amount,
    txId: payment.txId,
    explorerUrl: payment.explorerUrl,
    settlementStatus: "confirmed",
    sender: payment.payerAddress || payment.receiverAddress,
    receiver: payment.receiverAddress,
    confirmedAt: payment.settledAt,
  });
});

/**
 * Get payment status.
 */
router.get("/:paymentId/status", (req: Request, res: Response) => {
  const payment = getPayment(req.params.paymentId);
  if (!payment) {
    return res.status(404).json({
      error: { code: "not_found", message: "payment not found" },
    });
  }
  return res.json({
    paymentId: payment.paymentId,
    status: payment.status,
    txId: payment.txId,
    failureReason: payment.failureReason,
  });
});

export default router;