/**
 * x402 resource server for Algorand Testnet using REAL x402 packages.
 *
 * Uses @x402/core/server (x402ResourceServer + x402HTTPResourceServer) and
 * @x402/avm/exact/server (ExactAvmScheme). The resource server is protected by
 * the in-process x402 facilitator (self-facilitation).
 *
 * HTTP flow:
 * 1. Client requests POST /api/payment/optimize without payment → HTTP 402 +
 *    Payment-Required header (v2) generated by the real SDK.
 * 2. Client connects an Algorand wallet and builds a payment payload (v2).
 * 3. Client retries with `X-Payment` / `Payment-Signature` header.
 * 4. processHTTPRequest() verifies via the self-hosted facilitator /verify
 *    (signatures + on-chain simulation) → `payment-verified`.
 * 5. The route settles via processSettlement() → facilitator /settle submits the
 *    atomic transaction group to Algorand Testnet → REAL transaction ID.
 * 6. FastAPI backend is notified → task authorized.
 */
import {
  x402ResourceServer,
  x402HTTPResourceServer,
  type RoutesConfig,
  type HTTPAdapter,
  type HTTPRequestContext,
} from "@x402/core/server";
import { ExactAvmScheme } from "@x402/avm/exact/server";

import { config, ALGORAND_TESTNET } from "../config";
import { createFacilitatorClient } from "./facilitator";

let _resourceServer: x402ResourceServer | null = null;
let _httpServer: x402HTTPResourceServer | null = null;
let _initPromise: Promise<void> | null = null;

/**
 * Route configuration for the payment-protected endpoint.
 *
 * NOTE: paths are matched against `req.path` (Express strips the mount point).
 * This router is mounted at `/api/payment`, so the protectable pattern here is
 * `POST /optimize` (full URL: /api/payment/optimize).
 */
export const routesConfig: RoutesConfig = {
  "POST /optimize": {
    accepts: {
      scheme: config.scheme, // "exact"
      network: ALGORAND_TESTNET, // "algorand:SGO1..."
      payTo: config.receiverAddress,
      price: config.optimizationPrice, // USD decimal, e.g. 0.01
      maxTimeoutSeconds: 900,
    },
    resource: "Verified Energy Optimization Unlock",
    description: "UrjaSetu verified energy optimization service",
    serviceName: "urjasetu-x402-gateway",
    mimeType: "application/json",
    tags: ["energy", "optimization", "x402"],
    unpaidResponseBody: async () => ({
      contentType: "application/json",
      body: {
        error: {
          code: "payment_required",
          message: "x402 payment required to unlock verified optimization",
        },
      },
    }),
    settlementFailedResponseBody: async (_context, settleResult) => ({
      contentType: "application/json",
      body: {
        error: {
          code: "settlement_failed",
          message: settleResult.errorReason || settleResult.errorMessage || "settlement failed",
        },
      },
    }),
  },
};

/**
 * Build (singleton) the x402 resource server with the Algorand AVM exact scheme
 * registered against the testnet network. The facilitator client self-hosts to
 * the gateway's own /facilitator endpoints.
 */
export function createResourceServer(): x402ResourceServer {
  if (_resourceServer) return _resourceServer;

  const facilitatorClient = createFacilitatorClient();
  const resourceServer = new x402ResourceServer(facilitatorClient);
  resourceServer.register(ALGORAND_TESTNET, new ExactAvmScheme());

  _resourceServer = resourceServer;
  return resourceServer;
}

/**
 * Build (singleton) the HTTP resource server wrapping `createResourceServer()`
 * with the protected route configuration.
 */
export function createHTTPResourceServer(): x402HTTPResourceServer {
  if (_httpServer) return _httpServer;

  const httpServer = new x402HTTPResourceServer(createResourceServer(), routesConfig);
  _httpServer = httpServer;
  return httpServer;
}

/**
 * Lazily initialize the HTTP resource server (fetches supported kinds from the
 * in-process facilitator and validates route configuration). Safe to call on
 * every protected request: only the first invocation performs real work.
 *
 * Initialization happens lazily so the gateway is listening by the time the
 * self-hosted facilitator /supported endpoint is hit.
 */
export function ensureInitialized(): Promise<void> {
  const httpServer = createHTTPResourceServer();
  if (!_initPromise) {
    _initPromise = httpServer.initialize().catch((err: unknown) => {
      _initPromise = null; // allow a retry on the next request
      throw err;
    });
  }
  return _initPromise;
}

/**
 * Build the HTTP request context used by `processHTTPRequest`.
 * The payment header is read from `Payment-Signature` or `X-Payment`.
 */
export function buildRequestContext(
  adapter: HTTPAdapter,
  path: string,
  method: string,
  paymentHeader?: string,
): HTTPRequestContext {
  return { adapter, path, method, paymentHeader };
}

